/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DetailedWeatherPageRouteImport } from './routes/DetailedWeatherPage'
import { Route as IndexRouteImport } from './routes/index'

const DetailedWeatherPageRoute = DetailedWeatherPageRouteImport.update({
  id: '/DetailedWeatherPage',
  path: '/DetailedWeatherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/DetailedWeatherPage': typeof DetailedWeatherPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/DetailedWeatherPage': typeof DetailedWeatherPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/DetailedWeatherPage': typeof DetailedWeatherPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/DetailedWeatherPage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/DetailedWeatherPage'
  id: '__root__' | '/' | '/DetailedWeatherPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailedWeatherPageRoute: typeof DetailedWeatherPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/DetailedWeatherPage': {
      id: '/DetailedWeatherPage'
      path: '/DetailedWeatherPage'
      fullPath: '/DetailedWeatherPage'
      preLoaderRoute: typeof DetailedWeatherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailedWeatherPageRoute: DetailedWeatherPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
